# Generated by Django 4.2.7 on 2025-09-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_pass',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
