# Generated by Django 4.2.7 on 2025-09-24 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='temptoken',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='TempToken',
        ),
    ]
