# Generated by Django 4.2.7 on 2025-09-25 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='last_pass',
        ),
    ]
